<a href="https://colab.research.google.com/github/mananmani1/mananmani1/blob/main/tf_variable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

creating variabl

In [3]:
tf.Variable(1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [4]:
a = tf.Variable([1,2,3])
a

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [5]:
a.shape

TensorShape([3])

In [6]:
a.name

'Variable:0'

In [7]:
a.dtype

tf.int32

In [8]:
a.numpy()

array([1, 2, 3], dtype=int32)

In [9]:
array = tf.Variable([1,1.2,True])
array

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1. , 1.2, 1. ], dtype=float32)>

In [10]:
array = tf.Variable([False,True])
array

<tf.Variable 'Variable:0' shape=(2,) dtype=bool, numpy=array([False,  True])>

In [11]:
array = tf.Variable([3 + 5j])
array

<tf.Variable 'Variable:0' shape=(1,) dtype=complex128, numpy=array([3.+5.j])>

**create variale from consatnt**

In [12]:
c = tf.constant([1,1.2])
c

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1. , 1.2], dtype=float32)>

In [13]:
v = tf.Variable(c)
v

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1. , 1.2], dtype=float32)>

re shaping of variable


In [36]:
array = tf.Variable([1,2,3,4])
array

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [39]:
val =tf.reshape(array, (2,2))
val

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [40]:
tf.argmax(val)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [41]:
tf.convert_to_tensor(val)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [42]:
array

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [43]:
array.assign([5,6,7,8])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([5, 6, 7, 8], dtype=int32)>

In [44]:
array

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([5, 6, 7, 8], dtype=int32)>

assign other memory location

In [46]:
array.assign_add([11,12,13,14])


<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([16, 18, 20, 22], dtype=int32)>